### PR TITLE
fix: array index counting resulting in misplaced replacements

### PR DESCRIPTION
**Pull request by splaw88**
related to issue #34

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
@splaw88 Thanks for this fix. Can you add some unit tests?

**Comment by splaw88** [comment]
Sure!

**Comment by AndersDJohnson** [comment]
@splaw88 I'll see if I can get to it. Haven't published to Maven for some time and I recall it being a bit tedious and complicated, at least compared to npm for example, but I'll try to recall the right steps.

**Comment by splaw88** [comment]
@AndersDJohnson so how's it going? Will you be able to merge and release?

**Pull request merged**
